[package]
name = "adventofcode"
version = "0.1.0"
edition = "2021"

[dependencies]
md-5 = "0.10.6"
itertools = "0.12.0"
num-integer = "0.1.45"

[profile.release]
lto = true
codegen-units = 1
strip = true
panic = "abort"
