[package]
name = "adventofcode_2023"
version = "0.1.0"
edition = "2021"

[dependencies]
phf = { version = "0.11.2", features = ["macros"] }

[profile.release]
lto = true
codegen-units = 1
strip = true
panic = "abort"
